# Generated by Django 2.2.8 on 2021-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
    ]
