# Generated by Django 2.2.8 on 2021-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available_variation',
            new_name='available_variations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variations',
            field=models.ManyToManyField(to='store_app.Variation'),
        ),
    ]
