# Generated by Django 2.2.8 on 2021-07-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20210702_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='custom_base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='custom_price_with_all_variations',
            field=models.FloatField(default=0.0),
        ),
    ]
