# Generated by Django 2.2.8 on 2021-07-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20210703_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store_app.ColorVariation'),
            preserve_default=False,
        ),
    ]
